### ISSUE TITLE
rosdep init error

### ISSUE THREAD

**Issue by huanglidongTX2** [jetsonhacks/installROS#1]
I followed this website to install ROS on TX2 （ubuntu18.04）http://wiki.ros.org/melodic/Installation/Ubuntu.
but when i do the step: sudo rosdep init ,it will be wrong :
RROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.

I don't know how to solve it , please help me, thx.

**Comment by jetsonhacks** [comment]
You probably have a communication error reaching the server. This is not related to this repository.
