### ISSUE TITLE
L4T linux supported

### ISSUE THREAD

**Issue by praveenputhettu** [jetsonhacks/installROS#3]
Can i use this to install ROS melodic in Jetson TX1 containing L4T linux?

**Comment by jetsonhacks** [comment]
If the TX1 is running an Ubuntu version 18.04 of L4T. I believe that these switched over from 16.04 to 18.04 with L4T > 31.X

**Comment by jetsonhacks** [comment]
You should be able to. Check out the current version and see if it works.
